name: Kraken Tests
on:
  push:
    branches:
     - main
  pull_request:
    branches:
     - main
jobs:
  kraken-tests:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    env:
      GHOST_VERSION: 4.41
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - uses: nanasess/setup-chromedriver@v1
    - name: Setup docker
      uses: docker-practice/actions-setup-docker@v1
    - name: Pull docker image
      run: docker image pull ghost:${GHOST_VERSION}
    - name: Install system dependencies
      run: sudo apt-get install -y android-tools-adb
    - name: Install dependencies
      run: npm ci
    - name: Run kraken tests
      run: npm run kraken
